---
- name: install development tool packages
  apt: name={{item}} state=present
  with_items:
    - vim-gtk       

- name: install node version manager
  shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.2/install.sh | bash
  sudo_user: james

- name: install node
  shell: zsh -c ". ~/.zshrc && nvm install v4.2.6"
  sudo_user: james
