---
# Linux Mint identifies family as LinuxMint which causes many playbooks to fail.
- name: Set ansible OS family to debian
  set_fact: ansible_os_family="Debian"         

- name: set default keymap to extd/gb
  copy: src=../files/keyboard dest=/etc/default/keyboard backup=yes

- name: reconfigure keyboard pkg
  command: dpkg-reconfigure keyboard-configuration -f noninteractive

- name: Remove webapps
  apt: name=unity-webapps-service state=absent

- name: add xdg autostart to disable web search
  copy: src=../files/disablewebsearch.desktop dest=/etc/xdg/autostart/disablewebsearch.desktop

- name: install chrome apt-key
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

- name: add google chrome repo
  copy: src=../files/google.list dest=/etc/apt/sources.list.d/google.list mode=0644

- name: update apt
  apt: update_cache=yes

- name: install packages
  apt: name={{item}} state=present
  with_items:
    - google-chrome-stable
    - zsh
    - curl
    - texlive 
    - texlive-latex-extra
    - git
