---
# Setting up my user for development, note: password is same as username and
# will need to be reset
- name: Setup dev user
  user: name=james createhome=yes state=present password=$6$HxIaFZPe$qGv1unUigyfODc370oV4AQD5W./T6UWbMfxQOD1jrRdIJlrVN4wa31YYXfnj4Jzb8Cv9iTgEnJdmP1zVZKzY50
