--- 
# Note: Add new galaxy roles into requirements.txt so they get installed.
- hosts: controller
  sudo: true
  roles:
  - system-setup        
  - user-setup  
  - { role: playlist.java, java_packages: oracle-java8-installer }
  - geerlingguy.git  
  - git-setup
  - devtools  
  - devbox.chrome  
