--- 
# Note: Add new galaxy roles into requirements.txt so they get installed.
- hosts: controller
  sudo: true
  roles:
  - { role: system-setup, tags: [system-setup] }
  - { role: user-setup, tags: [user-setup] }
  - { role: playlist.java, java_packages: oracle-java8-installer }
  - geerlingguy.git  
  - devtools  
